wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.15.10
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1739057142.525853
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      - 71
      2:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      - 71
      3:
      - 23
      4: 3.11.7
      5: 0.15.10
      6: 4.35.2
      8:
      - 5
